version: '3.5'


services:
  postgres:
    container_name: postgres_travel
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "2432:5432"


volumes:
  postgres-db:
    driver: local
